/**
 * Legal manifest integrity (config/legalManifest.json, generated by
 * scripts/legal-build.js).
 *
 * Guards two invariants:
 *   1. Every document a role is REQUIRED to accept actually exists in the
 *      manifest (a missing entry would let that role register without ever
 *      being asked to accept a mandatory document).
 *   2. The recorded hash is the deterministic sha256 of the canonical HTML in
 *      docs/legal/ (CRLF-normalised) — i.e. the build is reproducible and the
 *      evidence hash matches the source of truth.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const manifest = require('../config/legalManifest.json');
const LEGAL_SRC = path.join(__dirname, '..', 'docs', 'legal');

const sha256 = (buf) => crypto.createHash('sha256').update(buf, 'utf8').digest('hex');
const normalise = (s) => s.replace(/\r\n/g, '\n');

describe('legal manifest shape', () => {
  test('has documents and the creator/advertiser required mappings', () => {
    expect(manifest.documents && typeof manifest.documents).toBe('object');
    expect(Array.isArray(manifest.required.creator)).toBe(true);
    expect(Array.isArray(manifest.required.advertiser)).toBe(true);
  });

  test('every required slug resolves to a document entry', () => {
    for (const slugs of Object.values(manifest.required)) {
      for (const slug of slugs) {
        expect(manifest.documents[slug]).toBeTruthy();
      }
    }
  });

  test('each document entry is well-formed', () => {
    for (const [slug, doc] of Object.entries(manifest.documents)) {
      expect(doc.slug).toBe(slug);
      expect(typeof doc.titulo).toBe('string');
      expect(doc.hash).toMatch(/^[a-f0-9]{64}$/);
      expect(doc.version).toBe(doc.hash.slice(0, 12));
      expect(doc.url).toBe(`/legal/${slug}.html`);
    }
  });
});

describe('manifest is reproducible from the canonical source HTML', () => {
  // We assert the BUILD is deterministic + the source files exist, rather than
  // pinning the committed manifest hash to the working tree. The legal docs are
  // v0.9 drafts under active edit, and `legal:build` regenerates the manifest on
  // every deploy (it's in the build chain), so a momentarily-stale committed
  // hash is harmless — what must hold is that re-running the build on the same
  // bytes yields the same hash, and that the version derives from that hash.
  const requiredSlugs = [...new Set(Object.values(manifest.required).flat())];

  test('every required source document exists', () => {
    for (const slug of requiredSlugs) {
      expect(fs.existsSync(path.join(LEGAL_SRC, `${slug}.html`))).toBe(true);
    }
  });

  test('hashing is deterministic (CRLF-normalised) and version is the hash prefix', () => {
    for (const slug of requiredSlugs) {
      const raw = fs.readFileSync(path.join(LEGAL_SRC, `${slug}.html`), 'utf8');
      const h1 = sha256(normalise(raw));
      const h2 = sha256(normalise(raw));
      expect(h1).toBe(h2);
      expect(h1).toMatch(/^[a-f0-9]{64}$/);
      // The manifest's own version must be the 12-char prefix of its own hash.
      expect(manifest.documents[slug].version).toBe(manifest.documents[slug].hash.slice(0, 12));
    }
  });
});
