import { lazy } from 'react'

// Blog post registry — add new posts here and they auto-appear on /blog and sitemap.
// Content is rendered by each post's component (lazy-loaded).
// Updated: 2026-05-07 — 18 posts total

export const BLOG_POSTS = [
  {
    slug: 'casos-exito-monetizar-telegram-channelad',
    component: lazy(() => import('./posts/CasosExito')),
    title: '5 creadores que monetizan sus canales con Channelad: casos reales',
    description: 'Datos reales, ingresos reales. 5 creadores de canales de Telegram y Discord que generan ingresos recurrentes con publicidad a traves de Channelad.',
    category: 'Monetizacion',
    platform: 'telegram',
    date: '2026-05-02',
    readTime: '12 min',
    lang: 'es',
    keywords: ['casos exito telegram monetizacion', 'channelad creadores', 'monetizar telegram casos reales', 'ganar dinero telegram ejemplos', 'channelad opiniones'],
  },
  {
    slug: 'media-kit-canal-telegram',
    component: lazy(() => import('./posts/MediaKitTelegram')),
    title: 'Como crear un media kit para tu canal de Telegram que consiga anunciantes en 2026',
    description: 'El media kit es el documento que convierte tu canal en un negocio. Los 7 elementos que debe tener, como obtener estadisticas y errores comunes.',
    category: 'Guias',
    platform: 'telegram',
    date: '2026-04-30',
    readTime: '10 min',
    lang: 'es',
    keywords: ['media kit telegram', 'como conseguir anunciantes telegram', 'media kit canal telegram', 'plantilla media kit telegram', 'vender publicidad telegram'],
    faq: [
      { question: '\u00bfQu\u00e9 debe incluir un media kit de Telegram?', answer: 'Los 7 elementos esenciales: nombre y descripcion del canal, estadisticas clave (suscriptores, vistas, engagement), demografia de audiencia, formatos y precios, ejemplos de campanas anteriores, testimonios y datos de contacto.' },
      { question: '\u00bfC\u00f3mo obtener estadisticas de mi canal de Telegram?', answer: 'Usa TGStat (gratuito, muestra datos publicos), bots de estadisticas como @ChannelAnalyticsBot, o lleva un spreadsheet manual con datos semanales para mostrar tendencias de crecimiento.' },
    ],
  },
  {
    slug: 'publicidad-comunidades-online-guia-anunciantes',
    component: lazy(() => import('./posts/PublicidadComunidades')),
    title: 'Como hacer publicidad en comunidades online: guia para anunciantes 2026',
    description: 'Guia completa para anunciarse en comunidades de Telegram, WhatsApp y Discord. Estrategia, presupuesto, metricas y como medir el ROI.',
    category: 'Guias',
    platform: 'telegram',
    date: '2026-04-28',
    readTime: '14 min',
    lang: 'es',
    keywords: ['publicidad comunidades online', 'anunciarse comunidades', 'marketing comunidades 2026', 'publicidad telegram whatsapp discord', 'ROI publicidad comunidades'],
    faq: [
      { question: '\u00bfCu\u00e1nto cuesta anunciarse en comunidades online?', answer: 'Una campana minima viable cuesta 200-500 EUR (3-5 posts en diferentes canales). Para resultados estadisticamente significativos, planifica al menos 1.000 EUR en 4-6 semanas.' },
      { question: '\u00bfC\u00f3mo medir el ROI de publicidad en comunidades?', answer: 'Usa enlaces con UTM para trackear cada campana, crea landing pages dedicadas, asigna codigos de descuento unicos por canal, y compara el CPA con tus canales habituales (Meta Ads, Google Ads).' },
    ],
  },
  {
    slug: 'telegram-vs-whatsapp-vs-discord-publicidad',
    component: lazy(() => import('./posts/ComparativaPlataformas')),
    title: 'Telegram vs WhatsApp vs Discord: donde anunciarse en 2026',
    description: 'Comparativa completa entre las tres plataformas de comunidades para publicidad. CPM, engagement, formatos y recomendaciones por tipo de marca.',
    category: 'Comparativas',
    platform: 'telegram',
    date: '2026-04-25',
    readTime: '13 min',
    lang: 'es',
    keywords: ['telegram vs whatsapp publicidad', 'mejor plataforma publicidad comunidades', 'comparativa telegram whatsapp discord', 'donde anunciarse comunidades 2026'],
    faq: [
      { question: '\u00bfQu\u00e9 plataforma es mejor para anunciarse: Telegram, WhatsApp o Discord?', answer: 'Depende de tu marca. Consumo masivo: WhatsApp (mayor alcance). Tech/B2B: Telegram (mejor CPM). Gaming/Gen Z: Discord (mayor engagement). Estrategia full-funnel: las tres con Channelad.' },
      { question: '\u00bfD\u00f3nde es mas barato anunciarse en comunidades?', answer: 'Discord tiene los CPMs mas bajos (1,5-3 EUR en gaming). Telegram tiene el mejor ratio calidad-precio en nichos premium (finanzas, cripto). WhatsApp es el mas nuevo con precios en formacion.' },
    ],
  },
  {
    slug: 'publicidad-discord-marcas',
    component: lazy(() => import('./posts/PublicidadDiscordMarcas')),
    title: 'Publicidad en Discord para marcas: guia completa (2026)',
    description: 'Como anunciarse en servidores de Discord. Formatos, precios, como encontrar servidores verificados y por que el engagement en Discord supera a cualquier red social.',
    category: 'Guias',
    platform: 'discord',
    date: '2026-04-23',
    readTime: '11 min',
    lang: 'es',
    keywords: ['publicidad discord marcas', 'anunciarse discord', 'marketing discord servidores', 'discord ads marcas', 'publicidad servidores discord'],
    faq: [
      { question: '\u00bfCu\u00e1nto cuesta anunciarse en un servidor de Discord?', answer: 'Los precios varian segun el tamano del servidor y el formato. Un post en un canal de anuncios cuesta entre 15-80 EUR en servidores de 1.000-10.000 miembros activos. Un evento patrocinado puede costar 100-500 EUR.' },
      { question: '\u00bfQu\u00e9 metricas pedir antes de pagar publicidad en Discord?', answer: 'Pide siempre: miembros activos vs totales, tasa de actividad diaria, capturas de estadisticas del servidor, y si es posible, resultados de campanas anteriores.' },
    ],
  },
  {
    slug: 'como-monetizar-servidor-discord',
    component: lazy(() => import('./posts/MonetizarDiscord')),
    title: 'Como monetizar un servidor de Discord en 2026: guia para administradores',
    description: 'Las 5 formas de ganar dinero con tu servidor de Discord. Publicidad, roles premium, merchandising y mas. Con datos de referencia de ingresos.',
    category: 'Monetizacion',
    platform: 'discord',
    date: '2026-04-21',
    readTime: '14 min',
    lang: 'es',
    keywords: ['monetizar servidor discord', 'ganar dinero discord', 'publicidad discord servidor', 'discord para creadores', 'monetizacion discord 2026'],
    faq: [
      { question: '\u00bfPaga Discord a los administradores de servidores?', answer: 'Discord no paga directamente. Los ingresos vienen de vender publicidad a marcas, roles premium, merchandising y servicios de comunidad. Servidores de 5.000-15.000 miembros activos pueden generar 200-600 EUR/mes.' },
      { question: '\u00bfCu\u00e1ntos miembros necesito para monetizar en Discord?', answer: 'Puedes empezar desde 500 miembros activos. El punto optimo es 2.000+, donde las marcas empiezan a pagar tarifas competitivas por acceder a tu comunidad.' },
      { question: '\u00bfEs legal cobrar por publicidad en Discord?', answer: 'Si, es completamente legal. Discord permite que los administradores moneticen sus servidores mediante publicidad, siempre que cumplan los terminos de servicio de la plataforma.' },
    ],
  },
  {
    slug: 'mejores-canales-whatsapp-espanol',
    component: lazy(() => import('./posts/MejoresCanalesWhatsApp')),
    title: 'Los mejores canales de WhatsApp en espanol (2026): guia por categorias',
    description: 'Seleccion curada de los canales de WhatsApp mas activos en espanol. Por categoria: finanzas, tecnologia, marketing, noticias, emprendimiento y fitness.',
    category: 'Guias',
    platform: 'whatsapp',
    date: '2026-04-18',
    readTime: '10 min',
    lang: 'es',
    keywords: ['mejores canales whatsapp', 'canales whatsapp espanol', 'canales whatsapp recomendados', 'whatsapp canales 2026', 'canales whatsapp seguir'],
  },
  {
    slug: 'publicidad-canales-whatsapp-marcas',
    component: lazy(() => import('./posts/PublicidadWhatsAppMarcas')),
    title: 'Publicidad en canales de WhatsApp: guia completa para marcas (2026)',
    description: 'Como anunciarse en canales de WhatsApp. Formatos, precios reales, como encontrar canales verificados y errores que debes evitar como marca en 2026.',
    category: 'Guias',
    platform: 'whatsapp',
    date: '2026-04-16',
    readTime: '12 min',
    lang: 'es',
    keywords: ['publicidad whatsapp canales marcas', 'anunciarse whatsapp canales', 'comprar publicidad whatsapp', 'marketing whatsapp 2026', 'publicidad canales whatsapp'],
    faq: [
      { question: '\u00bfCu\u00e1nto cuesta anunciarse en un canal de WhatsApp?', answer: 'Depende del nicho y tamano del canal. Un post patrocinado en un canal de 5.000-10.000 seguidores cuesta entre 30-120 EUR. La tasa de apertura en WhatsApp supera el 80%, lo que lo hace mas rentable que email marketing.' },
      { question: '\u00bfC\u00f3mo encontrar canales de WhatsApp para anunciarse?', answer: 'No hay un directorio centralizado todavia. La forma mas eficiente es usar un marketplace como Channelad, que ofrece canales verificados con metricas auditadas y pago protegido por escrow.' },
    ],
  },
  {
    slug: 'crear-canal-telegram-monetizar',
    component: lazy(() => import('./posts/CrearCanalTelegram')),
    title: 'Como crear un canal de Telegram desde cero y monetizarlo en 2026',
    description: 'Tutorial paso a paso para crear un canal de Telegram rentable: desde elegir el nicho hasta cobrar tu primer anuncio. Con estrategia de contenido y datos de referencia.',
    category: 'Guias',
    platform: 'telegram',
    date: '2026-04-11',
    readTime: '15 min',
    lang: 'es',
    keywords: ['como crear canal telegram', 'canal telegram ganar dinero', 'crear canal telegram desde cero', 'monetizar telegram principiantes', 'telegram para creadores'],
    faq: [
      { question: '\u00bfCu\u00e1ntos suscriptores necesito para monetizar un canal de Telegram?', answer: 'Puedes empezar a monetizar con 500 suscriptores activos. El punto optimo es 2.000+, donde los anunciantes pagan tarifas competitivas. Lo importante es el engagement, no el numero absoluto.' },
      { question: '\u00bfEs gratis crear un canal de Telegram?', answer: 'Si, crear un canal de Telegram es completamente gratis. No necesitas pagar nada para crearlo, publicar contenido ni crecer. Los costes solo aparecen si decides invertir en publicidad para crecer mas rapido.' },
      { question: '\u00bfCu\u00e1nto tiempo se tarda en llegar a 1.000 suscriptores?', answer: 'Con publicacion diaria y estrategia activa de crecimiento (cross-posting en grupos, colaboraciones, redes sociales), entre 2 y 4 meses. Sin estrategia, puede tardar 6-12 meses o mas.' },
    ],
  },
  {
    slug: 'cuanto-cobrar-publicidad-telegram',
    component: lazy(() => import('./posts/CuantoCobrarPublicidad')),
    title: 'Cuanto cobrar por publicidad en Telegram: calculadora y precios reales 2026',
    description: 'Formula exacta, tabla de CPMs por nicho y calculadora interactiva para poner el precio correcto a la publicidad en tu canal de Telegram.',
    category: 'Monetizacion',
    platform: 'telegram',
    date: '2026-04-09',
    readTime: '12 min',
    lang: 'es',
    keywords: ['cuanto cobrar publicidad telegram', 'precio publicidad telegram', 'CPM telegram canal', 'tarifas anuncios telegram', 'precios publicidad canal telegram'],
    faq: [
      { question: '\u00bfQu\u00e9 es el CPM en Telegram?', answer: 'El CPM (Coste Por Mil) es el precio que un anunciante paga por cada 1.000 impresiones de su anuncio. En Telegram varia por nicho: cripto (6-12 EUR), finanzas (5-10 EUR), tecnologia (4-8 EUR), gaming (1,5-3 EUR).' },
      { question: '\u00bfCu\u00e1nto cobrar por un post en un canal de 5.000 suscriptores?', answer: 'Depende del nicho. Usando la formula (suscriptores x CPM) / 1.000: un canal de tecnologia cobraria ~30 EUR por post estandar y ~60 EUR por post fijado 24h. Un canal de finanzas cobraria ~37 EUR y ~75 EUR respectivamente.' },
      { question: '\u00bfEs mejor cobrar por CPA o por CPM en Telegram?', answer: 'Para la mayoria de canales, CPM es mas predecible y rentable. El CPA (Coste Por Accion) solo conviene si tu audiencia tiene tasas de conversion muy altas y el producto paga comisiones elevadas.' },
    ],
  },
  {
    slug: 'cuanto-paga-telegram-por-canal',
    component: lazy(() => import('./posts/CuantoPagaTelegram')),
    title: 'Cuanto paga Telegram por canal en 2026: la respuesta real',
    description: 'Telegram no paga directamente, pero tu canal SI puede generar ingresos. Datos de referencia de cuanto ganan los canales de Telegram en el mercado hispanohablante.',
    category: 'Monetizacion',
    platform: 'telegram',
    date: '2026-04-07',
    readTime: '10 min',
    lang: 'es',
    keywords: ['cuanto paga telegram por canal', 'cuanto gana un canal de telegram', 'monetizacion telegram 2026', 'telegram ingresos canal', 'ganar dinero telegram'],
    faq: [
      { question: '\u00bfCu\u00e1nto paga Telegram por 1.000 visualizaciones?', answer: 'Telegram paga entre 0,10 y 0,50 EUR por mil impresiones a traves de su programa oficial de anuncios (Fragment). Pero la publicidad directa genera entre 5 y 10 veces mas: de 1,5 a 12 EUR por mil impresiones dependiendo del nicho.' },
      { question: '\u00bfSe puede vivir de un canal de Telegram?', answer: 'Con un solo canal es dificil salvo que tengas mas de 30.000 suscriptores en un nicho premium. Pero como ingreso complementario, canales de 5.000-10.000 suscriptores generan entre 200 y 500 EUR mensuales con publicidad directa.' },
      { question: '\u00bfCu\u00e1ndo empieza a pagar Telegram?', answer: 'La monetizacion oficial de Telegram (Fragment) requiere un minimo de 1.000 suscriptores. Para publicidad directa a traves de marketplaces como Channelad, puedes empezar desde 500 suscriptores activos.' },
    ],
  },
  {
    slug: 'publicidad-en-discord-guia-completa',
    component: lazy(() => import('./posts/PublicidadDiscord')),
    title: 'Publicidad en Discord: Guia completa 2026',
    description: 'Todo lo que necesitas saber para hacer publicidad en servidores de Discord. Formatos, precios, mejores practicas y como encontrar servidores verificados.',
    category: 'Guias',
    platform: 'discord',
    date: '2026-04-10',
    readTime: '15 min',
    lang: 'es',
    keywords: ['publicidad discord', 'anuncios discord', 'discord ads', 'marketing discord', 'servidores discord publicidad'],
  },
  {
    slug: 'monetizar-canal-telegram-espana',
    component: lazy(() => import('./posts/MonetizarTelegram')),
    title: 'Como monetizar un canal de Telegram en 2026 [Guia completa]',
    description: 'Descubre cuanto se puede ganar con un canal de Telegram, que plataformas usar y como poner precios. Guia actualizada con datos del mercado hispanohablante.',
    category: 'Monetizacion',
    platform: 'telegram',
    date: '2026-04-07',
    dateModified: '2026-04-07',
    readTime: '14 min',
    lang: 'es',
    keywords: ['monetizar telegram', 'como monetizar un canal de telegram', 'ganar dinero telegram', 'publicidad telegram', 'vender publicidad telegram', 'telegram espana'],
    faq: [
      { question: '\u00bfCu\u00e1ntos suscriptores necesito para monetizar un canal de Telegram?', answer: 'Puedes empezar a monetizar con 500 suscriptores activos. El punto optimo es a partir de 2.000 suscriptores, donde los anunciantes empiezan a pagar tarifas competitivas.' },
      { question: '\u00bfCu\u00e1nto paga Telegram por canal?', answer: 'Telegram no paga directamente. Los ingresos provienen de vender publicidad: canales de 1.000-3.000 suscriptores generan entre 40-120 EUR/mes; los de 100.000+ pueden llegar a 15.000 EUR/mes.' },
      { question: '\u00bfC\u00f3mo poner precio a los anuncios en mi canal de Telegram?', answer: 'Usa la formula: Precio = (Suscriptores activos x CPM del nicho) / 1.000. El CPM varia por nicho: finanzas (5-10 EUR), cripto (6-12 EUR), gaming (1,5-3 EUR).' },
    ],
  },
  {
    slug: 'telega-in-alternatives',
    component: lazy(() => import('./posts/TelegaAlternatives')),
    title: 'Telega.in alternatives: Best Telegram ad marketplaces in 2026',
    description: 'Looking for Telega.in alternatives? Compare the top Telegram advertising platforms with escrow payments, verified metrics and community-first approach.',
    category: 'Comparativas',
    platform: 'telegram',
    date: '2026-04-20',
    readTime: '13 min',
    lang: 'en',
    keywords: ['telega alternative', 'telega.in review', 'telegram advertising platform', 'buy telegram ads'],
  },
  {
    slug: 'como-monetizar-canal-whatsapp',
    component: lazy(() => import('./posts/MonetizarWhatsApp')),
    title: 'Como monetizar un canal de WhatsApp en 2026: guia completa para creadores',
    description: 'Guia paso a paso para ganar dinero con tu canal de WhatsApp. Las 4 formas de monetizar, cuanto se puede ganar y como empezar hoy.',
    category: 'Monetizacion',
    platform: 'whatsapp',
    date: '2026-04-14',
    readTime: '14 min',
    lang: 'es',
    keywords: ['monetizar canal whatsapp', 'ganar dinero canal whatsapp', 'publicidad whatsapp canales', 'whatsapp para creadores', 'monetizacion whatsapp 2026'],
    faq: [
      { question: '\u00bfPaga WhatsApp a los creadores de canales?', answer: 'Meta ha empezado a activar monetizacion nativa en WhatsApp desde 2025 (anuncios en Status y suscripciones de canal). Pero la mayoria de ingresos vienen de publicidad directa con anunciantes, igual que en Telegram.' },
      { question: '\u00bfCu\u00e1ntos seguidores necesito para monetizar un canal de WhatsApp?', answer: 'Para publicidad directa, desde 500 seguidores activos. Para la monetizacion nativa de Meta, los requisitos aun no estan publicados oficialmente en todos los paises.' },
      { question: '\u00bfPuedo poner publicidad en mi canal de WhatsApp?', answer: 'Si. Puedes publicar mensajes patrocinados de marcas en tu canal. La forma mas segura es hacerlo a traves de un marketplace con escrow como Channelad.' },
    ],
  },
  {
    slug: 'publicidad-en-whatsapp-guia-completa',
    component: lazy(() => import('./posts/PublicidadWhatsApp')),
    title: 'Publicidad en WhatsApp: Guía completa para anunciantes (2026)',
    description: 'Guía práctica para hacer publicidad en grupos y canales de WhatsApp. Formatos, precios reales, cómo encontrar comunidades verificadas y errores que debes evitar.',
    category: 'Guias',
    platform: 'whatsapp',
    date: '2026-04-14',
    readTime: '14 min',
    lang: 'es',
    keywords: ['publicidad whatsapp', 'anuncios whatsapp', 'marketing grupos whatsapp', 'comprar publicidad whatsapp', 'whatsapp ads'],
  },
  {
    slug: 'escrow-publicidad-digital',
    component: lazy(() => import('./posts/EscrowPublicidad')),
    title: 'Qué es el escrow en publicidad digital y por qué lo necesitas',
    description: 'Todo sobre el pago custodiado en publicidad: cómo funciona, por qué protege tu inversión y qué plataformas lo ofrecen. Con ejemplos reales de campañas.',
    category: 'Guias',
    platform: 'telegram',
    date: '2026-04-16',
    readTime: '12 min',
    lang: 'es',
    keywords: ['escrow publicidad', 'pago custodiado publicidad', 'proteger inversion publicitaria', 'escrow marketplace'],
  },
  {
    slug: 'publicidad-comunidades-vs-redes-sociales',
    component: lazy(() => import('./posts/ComunidadesVsRedes')),
    title: 'Publicidad en comunidades vs redes sociales: qué rinde más en 2026',
    description: 'Comparativa real entre publicidad en comunidades de Discord, Telegram y WhatsApp vs Instagram y TikTok Ads. CPM, CTR y conversiones con datos reales.',
    category: 'Comparativas',
    platform: 'discord',
    date: '2026-04-18',
    readTime: '13 min',
    lang: 'es',
    keywords: ['publicidad comunidades', 'comunidades vs redes sociales', 'marketing comunidades', 'CPM comunidades', 'publicidad nativa comunidades'],
  },
]

// Only return posts whose date is today or earlier (scheduled publication)
export function getPublishedPosts() {
  const today = new Date().toISOString().slice(0, 10)
  return BLOG_POSTS.filter(p => p.date <= today)
}

export function getPostBySlug(slug) {
  return getPublishedPosts().find(p => p.slug === slug)
}
