/**
 * Legal consent — single source of truth for clickwrap acceptance logic.
 *
 * Reads the build-generated manifest (config/legalManifest.json) which maps
 * each role to the set of legal documents it must accept, and carries the
 * current version + hash per document. Used by:
 *   - the registration / accept-terms controllers (record evidence),
 *   - buildUserResponse (derive `requiresTermsAcceptance`),
 *   - the frontend indirectly (it fetches the public copy of the same manifest).
 *
 * Evidence model (RGPD art. 7): each acceptance is appended as an immutable
 * entry { slug, version, hash, aceptadoEn, ip, userAgent }. `requiresAcceptance`
 * is DERIVED — a user needs (re)acceptance whenever a required document has no
 * accepted entry at the manifest's CURRENT version. Bumping a document's
 * content changes its hash → version → re-triggers the gate automatically.
 */

let manifest;
try {
  // Generated by scripts/legal-build.js; committed so it always exists.
  manifest = require('../config/legalManifest.json');
} catch {
  manifest = { documents: {}, required: {} };
}

const getManifest = () => manifest;

// IP / user-agent extraction — same precedence as lib/authAudit.js.
const clientIp = (req) =>
  req?.headers?.['x-forwarded-for']?.split(',')[0]?.trim() ||
  req?.ip ||
  req?.connection?.remoteAddress ||
  '';
const clientUA = (req) => req?.headers?.['user-agent'] || '';

/**
 * The document entries (with current version/hash) a role must accept.
 * Unknown roles (e.g. 'admin') have no required documents → [].
 */
function requiredDocsForRole(rol) {
  const slugs = manifest.required?.[rol] || [];
  return slugs.map((slug) => manifest.documents?.[slug]).filter(Boolean);
}

/**
 * Required documents the user has NOT accepted at the current version.
 * Returns an array of document entries (empty ⇒ fully consented).
 */
function missingConsents(user) {
  const required = requiredDocsForRole(user?.rol);
  if (!required.length) return [];
  const accepted = Array.isArray(user?.consentimientos) ? user.consentimientos : [];
  return required.filter(
    (doc) => !accepted.some((c) => c.slug === doc.slug && c.version === doc.version)
  );
}

function requiresAcceptance(user) {
  return missingConsents(user).length > 0;
}

/**
 * Build the consent evidence entries for every document a role must accept,
 * at the current manifest version, stamped with the request's IP + user-agent.
 * Pure (does not touch the DB) — used at registration time before the user doc
 * exists. Returns [] for roles with no required docs.
 */
function buildConsentEntries(rol, req) {
  const now = new Date();
  return requiredDocsForRole(rol).map((doc) => ({
    slug: doc.slug,
    version: doc.version,
    hash: doc.hash,
    aceptadoEn: now,
    ip: clientIp(req),
    userAgent: clientUA(req),
  }));
}

/**
 * Validate a client-submitted acceptance payload against the role's current
 * required set. The frontend only includes a {slug, version} when its box is
 * actively checked, so this enforces "all required boxes checked at the current
 * version" — and rejects stale versions. Returns { ok, missing: [slug...] }.
 */
function validateConsentPayload(rol, consents) {
  const submitted = Array.isArray(consents) ? consents : [];
  const missing = requiredDocsForRole(rol)
    .filter((doc) => !submitted.some((c) => c?.slug === doc.slug && c?.version === doc.version))
    .map((doc) => doc.slug);
  return { ok: missing.length === 0, missing };
}

/**
 * Append the role's required consents (at current version) to an existing user
 * and persist. Used by the accept-terms endpoint / gate. Returns the entries
 * added. No-op (returns []) when nothing is required.
 */
async function recordConsents(user, req) {
  const entries = buildConsentEntries(user?.rol, req);
  if (!entries.length) return [];
  user.consentimientos.push(...entries);
  await user.save();
  return entries;
}

module.exports = {
  getManifest,
  requiredDocsForRole,
  missingConsents,
  requiresAcceptance,
  buildConsentEntries,
  validateConsentPayload,
  recordConsents,
};
