/**
 * CanalAlert
 *
 * Capa 2 Fase 5 — one document per (canalId, alert-type, active) cluster.
 * Generated by FraudDetectionService after each CanalIntelligence
 * recompute. Auto-actions are recorded here AND applied to Canal.estado
 * for critical severity.
 *
 * Idempotency: the unique partial index on (canalId, type) WHERE
 * status='active' guarantees we never have two active alerts of the same
 * type for the same canal. The FraudDetectionService updates `evidence`
 * + `triggeredAt` instead of inserting a duplicate.
 *
 * Resolution: when an admin marks an alert as resolved, status flips to
 * 'resolved', resolvedAt/resolvedBy are set, and a future recompute can
 * fire a fresh alert of the same type (which will be a NEW document
 * because the partial unique index only covers status='active').
 *
 * Auto-actions taken on critical alerts:
 *   - pause_listings → Canal.estado = 'paused_review'. Admin must
 *     manually flip it back after investigating.
 *   - flag_review   → no Canal mutation; just visible in admin dashboard.
 *   - none          → log-only (info severity).
 */

'use strict';

const mongoose = require('mongoose');

const ALERT_TYPES = [
  'FOLLOWER_INCOHERENCE',        // declared vs observed mismatch
  'CATEGORY_MISMATCH',           // declared category vs NLP-detected dominant
  'ENGAGEMENT_ANOMALY_LOW',      // engagement_rate << threshold
  'ENGAGEMENT_ANOMALY_HIGH',     // engagement_rate >> threshold (suspect bot-boosted)
  'OCR_CONTRADICTS_PASSIVE',     // Capa 3 hook, not active yet
  'BOT_ADMIN_SUSPICION',         // botAdminSuspicionScore > threshold
  'DUPLICATE_CONTENT_FARM',      // uniqueContentRatio < threshold
  'SUDDEN_FOLLOWER_DROP',        // sharp follower decline = bought-followers cleanup
  'BRAND_SAFETY_VIOLATION',      // critical brand_safety_flags accumulate
];

const SEVERITIES = ['info', 'warning', 'critical'];
const STATUSES = ['active', 'resolved', 'dismissed'];
const AUTO_ACTIONS = ['none', 'pause_listings', 'flag_review'];

const CanalAlertSchema = new mongoose.Schema(
  {
    canalId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Canal',
      required: true,
      index: true,
    },

    type: { type: String, required: true, enum: ALERT_TYPES, index: true },
    severity: { type: String, required: true, enum: SEVERITIES, index: true },
    status: { type: String, required: true, enum: STATUSES, default: 'active', index: true },

    triggeredAt: { type: Date, default: Date.now, index: true },
    // Number of recompute cycles that have re-confirmed this alert. Useful
    // for "noise" detection — alerts that fire once and never again are
    // probably transient; ones that keep firing are real.
    reTriggerCount: { type: Number, default: 0 },
    lastTriggeredAt: { type: Date, default: Date.now },

    resolvedAt: { type: Date, default: null },
    resolvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Usuario',
      default: null,
    },
    resolutionNote: { type: String, default: '' },

    // Evidence is the snapshot of values that triggered this rule. Free-form
    // so each rule can record its own context (declared vs observed, the
    // current score, the percentile we're outside of, etc.). NOT used for
    // dedup — that's controlled by (canalId, type, status='active').
    evidence: { type: mongoose.Schema.Types.Mixed, default: {} },

    autoAction: { type: String, enum: AUTO_ACTIONS, default: 'none' },
    autoActionAppliedAt: { type: Date, default: null },

    // Snapshot of which formula/rule version triggered this — lets us
    // ignore old alerts after rule changes.
    ruleVersion: { type: String, default: '' },
  },
  {
    timestamps: true,
    strict: true,
    autoIndex: false,
  }
);

// Partial unique index — one ACTIVE alert per (canal, type). When an admin
// resolves an alert, status flips to 'resolved' and a future re-trigger
// creates a new document because this index doesn't cover non-active rows.
CanalAlertSchema.index(
  { canalId: 1, type: 1 },
  {
    unique: true,
    partialFilterExpression: { status: 'active' },
    name: 'canalId_type_active_unique',
  }
);

// Severity-sorted lookups for admin dashboards
CanalAlertSchema.index({ status: 1, severity: 1, triggeredAt: -1 });
CanalAlertSchema.index({ canalId: 1, status: 1, triggeredAt: -1 });

module.exports = mongoose.model('CanalAlert', CanalAlertSchema);
module.exports.ALERT_TYPES = ALERT_TYPES;
module.exports.SEVERITIES = SEVERITIES;
module.exports.STATUSES = STATUSES;
module.exports.AUTO_ACTIONS = AUTO_ACTIONS;
